# Generated by Django 4.1.7 on 2023-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_templatetags', '0002_alter_menu_options_remove_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элемент меню'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок меню'),
        ),
    ]
